# Generated by Django 4.0.7 on 2022-09-30 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemoKeyWord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(max_length=200)),
                ("important", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MemoSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("cookie", models.FileField(blank=True, null=True, upload_to="source")),
            ],
        ),
        migrations.CreateModel(
            name="MetaMemo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("picture", models.ImageField(blank=True, null=True, upload_to="memo")),
                ("facebook_handle", models.CharField(blank=True, max_length=200)),
                ("instagram_handle", models.CharField(blank=True, max_length=200)),
                ("twitter_handle", models.CharField(blank=True, max_length=200)),
                ("youtube_handle", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="news")),
            ],
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("text", models.TextField(blank=True)),
                ("content_date", models.DateTimeField(null=True)),
                (
                    "metamemo",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="metamemoapp.metamemo"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="metamemoapp.newssource"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsCover",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_date", models.DateTimeField(null=True)),
                ("media", models.ImageField(blank=True, upload_to="cover")),
                (
                    "source",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="metamemoapp.newssource"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoNews",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("text", models.TextField(blank=True)),
                ("content_date", models.DateTimeField(null=True)),
                ("source", models.CharField(max_length=200)),
                (
                    "metamemo",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="metamemoapp.metamemo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_url", models.URLField(max_length=500)),
                ("original_id", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial"),
                            ("DOWNLOADING", "Downloading"),
                            ("DOWNLOADED", "Downloaded"),
                            ("FAILED_DOWNLOAD", "Download Failed"),
                            ("TRANSCRIBING", "Transcribing"),
                            ("TRANSCRIBED", "Transcribed"),
                            ("FAILED_TRANSCRIBE", "Transcribe Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transcription", models.TextField(blank=True)),
                ("media", models.FileField(blank=True, upload_to="media")),
                (
                    "mediatype",
                    models.CharField(blank=True, choices=[("VIDEO", "Video"), ("IMAGE", "Image")], max_length=20),
                ),
                ("progress", models.FloatField(default=0)),
                (
                    "source",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="metamemoapp.memosource"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField(blank=True)),
                ("extraction_date", models.DateTimeField(null=True)),
                ("content_date", models.DateTimeField(null=True)),
                ("url", models.URLField()),
                ("likes", models.IntegerField()),
                ("interactions", models.IntegerField()),
                ("shares", models.IntegerField(null=True)),
                ("raw", models.JSONField(blank=True, null=True)),
                ("original_id", models.CharField(max_length=500)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="metamemoapp.metamemo")),
                ("keyword", models.ManyToManyField(blank=True, to="metamemoapp.memokeyword")),
                ("medias", models.ManyToManyField(blank=True, to="metamemoapp.memomedia")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="metamemoapp.memosource")),
            ],
        ),
        migrations.CreateModel(
            name="MemoContext",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("context", models.TextField(blank=True)),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=500, null=True)),
                ("keyword", models.ManyToManyField(blank=True, to="metamemoapp.memokeyword")),
            ],
        ),
    ]
