# Generated by Django 4.0.7 on 2022-11-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metamemoapp", "0002_memoitem_metamemoapp_content_014163_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="memonews",
            index=models.Index(fields=["content_date"], name="metamemoapp_content_8a27c9_idx"),
        ),
        migrations.AddIndex(
            model_name="newscover",
            index=models.Index(fields=["content_date"], name="metamemoapp_content_d0c6fa_idx"),
        ),
        migrations.AddIndex(
            model_name="newsitem",
            index=models.Index(fields=["content_date"], name="metamemoapp_content_fa0728_idx"),
        ),
    ]
