# Generated by Django 4.0.7 on 2022-11-29 06:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamemoapp', '0005_auto_20221128_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='memocontext',
            name='search_data',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='memoitem',
            name='search_data',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='memomedia',
            name='search_data',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='search_data',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='memocontext',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_data'], name='metamemoapp_search__87d3a2_gin'),
        ),
        migrations.AddIndex(
            model_name='memoitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_data'], name='metamemoapp_search__c0ae13_gin'),
        ),
        migrations.AddIndex(
            model_name='memomedia',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_data'], name='metamemoapp_search__a13540_gin'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_data'], name='metamemoapp_search__b4ad4a_gin'),
        ),
    ]
