# Generated by Django 4.0.7 on 2023-07-03 15:09

from django.db import migrations


def migrate_handles(apps, schema_editor):
    MetaMemo = apps.get_model("metamemoapp", "MetaMemo")

    # Fix name (acute)
    obj, _ = MetaMemo.objects.get_or_create(name="Familia Bolsonaro")
    obj.name = "Família Bolsonaro"
    obj.save()

    social_handles = {
        "Jair Bolsonaro": {
            "facebook": "jairmessias.bolsonaro",
            "instagram": "jairmessiasbolsonaro",
            "telegram": "jairbolsonarobrasil",
            "twitter": "jairbolsonaro",
            "youtube": "UC8hGUtfEgvvnp6IaHSAg1OQ",
        },
        "Carlos Bolsonaro": {
            "facebook": "cbolsonaro",
            "instagram": "carlosbolsonaro",
            "telegram": "bolsonarocarlos",
            "twitter": "carlosbolsonaro",
            "youtube": "UCBrntWupyTRnnsRy3dA4VdA",
        },
        "Eduardo Bolsonaro": {
            "facebook": "bolsonaro.enb",
            "instagram": "bolsonarosp",
            "telegram": "depeduardobolsonaro",
            "twitter": "bolsonaroSP",
            "youtube": "UCkR6xPOHhpjq3wnFchVI4sg",
        },
        "Flávio Bolsonaro": {
            "facebook": "flaviobolsonaro",
            "instagram": "flaviobolsonaro",
            "telegram": "senadorflaviobolsonaro",
            "twitter": "FlavioBolsonaro",
            "youtube": "UCl2HptoHv6PjZMQAwTdA--Q",
        },
        "Família Bolsonaro": {
        },
    }
    for name, handles in social_handles.items():
        obj, _ = MetaMemo.objects.get_or_create(name=name)
        for network, username in handles.items():
            if not username:
                continue
            setattr(obj, f"{network}_handle", username)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('metamemoapp', '0008_metamemo_telegram_handle'),
    ]

    operations = [
        migrations.RunPython(migrate_handles),
    ]
