version: "3.4"

services:
 vite_docker:
   image: node:alpine
   container_name: "${DOCKER_NAME}"
   entrypoint: /bin/sh
   env_file:
     - .env
   user: "${UID}:${GID}"
   ports:
     - "${HOST_PORT}:${CONTAINER_PORT}"
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
   network_mode: host
