version: "3.9"
services:
  database:
    image: mariadb:10.3.34
    ports: 
      - 33060:3306
    environment:
      - MARIADB_ROOT_PASSWORD

  broker:
    image: redis:6
    ports:
      - 63790:6379

  storage:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: ["server", "/data", "--console-address", ":9001"]
